### ISSUE TITLE
can you please desribe all the requirements to run this code???

### ISSUE THREAD

**Issue by Babitababy** [ahmed-shameem/Projects#1]

**Comment by ahmed-shameem** [comment]
If you are trying to run AbetaCRO.py then go to line no. -398, change the datasetlist as per your requirement (whichever datasets you want to run and make sure that the code and the datasets are in the same directory). The same goes with iEBMO.py, go to line no. - 217, change ImageNamelist as per your requirement  (whichever datasets you want to run and make sure that the code and the datasets are in the same directory). These codes will run properly as long as there is not a single irregularity in the dataset.
