### ISSUE TITLE
What kind of parameters need to be change?

### ISSUE THREAD

**Issue by sk-mohiuddin** [ahmed-shameem/Projects#5]
Dear, 
I have a feature file of 2888 dimensions and the binary class (0 or 1) is added at the last column (i.e., new dim 2889) of 3000 rows. Could you help me to run your program on this file? Which parameters need to be changed? (e.g. currFeat= 20000). Thanks.

**Comment by ahmed-shameem** [comment]
Depends on your use-case. These are the following parameters that are used in AbetaCRO:
Ngen = 30                # Number of generations
N  = 5                   # MxN: reef size
M  = 5                    # MxN: reef size
Fb = 0.6                   # Broadcast prob.
Fa = 0.4                   # Asexual reproduction prob.
Fd = 0.1                   # Fraction of the corals to be eliminated in the depredation operator.
r0 = 0.6                   # Free/total initial proportion
k  = 3                     # Number of opportunities for a new coral to settle in the reef
Pd = 0.1                   # Depredation prob.
omega = 0.9
ke = 0.2

You don't have to worry about the dimension of your dataset, that will be taken care by the code itself. You can tune the above parameters to obtain the best results.
