### ISSUE TITLE
AbetaCRO script csv dataset

### ISSUE THREAD

**Issue by lucass235** [ahmed-shameem/Projects#6]
Friend, where do I get the following csv files "BreastCancer.csv", "BreastEW.csv", "CongressEW.csv", "Exactly.csv", "Exactly2.csv", "HeartEW.csv", "Ionosphere.csv", "Lymphography. csv", "M-of-n.csv", "PenglungEW.csv", "Sonar.csv", "SpectEW.csv", "Tic-tac-toe.csv", "Vote.csv", "Wine.csv", "Zoo.csv", "KrVsKpEW.csv", "WaveformEW.csv that you use in the Abeta CRO file

**Comment by ahmed-shameem** [comment]
https://github.com/ahmed-shameem/Feature_selection/tree/master/UCI_datasets
